name: "Podcast Generator"
author: "Ray Villalobos"
description: "Generates a feed for podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    desctption: The commiters email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    descriptio: The committer's name
    required: true
    default: ${{ github.actor }}
